---
# Defining a Play to ping all hosts in the inventory
- name: Ping all hosts
  hosts: k3s_cluster    # Specify the group name from inventory, e.g., 'k3s_cluster'
  become: false         # if true, will use sudo to run tasks as root; else as non-root user, e.g., ec2-user

  # A task has a name and an action/module to run
  tasks:
    - name: Ping the hosts
      ansible.builtin.ping:
    
    - name: Display host information
      ansible.builtin.debug:
        msg: "Host {{ inventory_hostname }} is reachable."
    
    # - name: Check Python interpreter path
    #   ansible.builtin.command: which python3
    #   register: python_path
    
    # - name: Display Python interpreter path
    #   ansible.builtin.debug:
    #     msg: "Python interpreter for host {{ inventory_hostname }} is located at {{ python_path.stdout }}"
    
    - name: Echo Message
      ansible.builtin.shell: echo "Hello from {{ inventory_hostname }}"
      register: echo_result
    
    - name: Print Message
      ansible.builtin.debug:
        msg: "{{ echo_result.stdout }}"