---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
d
  namespace: traefik-public
spec:
  secretName: mlops-wildcard-tls
  issuerRef:
    name: letsencrypt-cloudflare
    kind: ClusterIssuer
  dnsNames:
    - "*.mlops-club.org"
    - mlops-club.org
  secretTemplate:
    annotations:
      reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
      reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"

